export const BINARY_NAME = "ellamaka"
export const BINARY_TITLE = "Ellamaka"
export const VERSION_PREFIX = "ellamaka"
export const CHANNEL_RELEASE = "ellamaka"
export const CHANNEL_DEV = "ellamaka-main"
